apiVersion: v1
kind: ConfigMap
metadata:
  name: fahin-config
  namespace: fahin
data:
  DEBUG: "False"
  LLM_MODEL: "gpt-4o-mini"
  EMBEDDING_MODEL: "text-embedding-3-small"
  OUTBREAK_ALERT_THRESHOLD: "0.70"
  ANOMALY_ALERT_THRESHOLD: "3.0"
  FLOWER_SERVER_ADDRESS: "fahin-fl-svc:8080"
  ALLOWED_HOSTS: '["fahin.yourdomain.com"]'
  ALLOWED_ORIGINS: '["https://fahin.yourdomain.com"]'
